### ISSUE TITLE
add data version info in __info__

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/absearch#16]
useful to know which version of the data has been deployed. can be a md5 hash of the data file

**Comment by karlht** [comment]
This is now in the `__heartbeat__` endpoint, I'm pretty sure.

```
$ curl -i https://search.services.mozilla.com/__heartbeat__
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 29 Nov 2016 21:57:50 GMT
Content-Length: 100
Connection: keep-alive

{"schema_md5": "0b62a10d11c0daaeb6b706b4930fde7f", "config_md5": "143774ba03bba614fa48759e62b3d555"}
```

**Comment by tiftran** [comment]
Closing as this issue has been around for a while, not sure of current relevance, will reopen if there’s a need for it
