### ISSUE TITLE
Documentation for development

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/absearch#28]
1. Install a local Redis (`subprocess.Popen(['redis-server', '--port', '7777'], ...)`
1. Install `tox`
1. ? 

I'm having errors like this when running tests:

```
  File "absearch/.tox/py27/local/lib/python2.7/site-packages/boto/auth.py", line 989, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials
```

**Comment by tiftran** [comment]
Closing as this issue has been around for a while, not sure of current relevance, will reopen if there’s a need for it
