### ISSUE TITLE
reset redis on stage

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/absearch#3]
we should provide a way to reset redis on stage after load tests

**Comment by Natim** [comment]
Usually we add a ``__flush__`` endpoint which is active only in stage.

**Comment by tarekziade** [comment]
This solution was discarded by ops as being too dangerous. @Micheletto what should we do for this ?

**Comment by Micheletto** [comment]
How often do you think we'll need to do the resets in Stage?

**Comment by ametaireau** [comment]
Why is it too dangerous? (I'm asking because we're doing that for some other projecs)

**Comment by Micheletto** [comment]
I'm paranoid about the possibility of it being enabled in production.

**Comment by Natim** [comment]
There are possibility to make sure it will not be activated in production.

**Comment by tarekziade** [comment]
> There are possibility to make sure it will not be activated in production.

I tend to agree with Bob, nothing can be more secure than "the app can't do this" whatever option/firewall you set up.   I have experienced dramatic screw-up on ElasticSearch because it's easy to wipe out some stuff on a simple CURL call.

Now the problem to solve is to make sure QA folks have a way or an access to FLUSH on stage.

**Comment by tarekziade** [comment]
> How often do you think we'll need to do the resets in Stage?

After every QA load test

**Comment by tiftran** [comment]
Closing as redis is no longer being used
