### ISSUE TITLE
100% cohorts are chosen regardless of later 100% cohorts with more recent versions

### ISSUE THREAD

**Issue by mkaply** [mozilla-services/absearch#31]
I have no idea what the right thing to do is here, but it's becoming an issue as we do things with absearch that it wasn't meant to do. If you have something like this:

```
          "apr18-1": {
            "settings": {
              "searchDefault": "Google",
              "visibleDefaultEngines": ["amazondotcom", "bing", "google-2018", "twitter", "wikipedia", "ddg"]
            },
            "filters": {
              "sampleRate": 100,
              "products": ["firefox"],
              "channels": ["esr"],
              "minVersion": 52.6
            },
            "interval": 86400
          },
          "apr18-2": {
            "settings": {
              "searchDefault": "Google",
              "visibleDefaultEngines": ["amazondotcom", "bing", "ebay", "google-2018", "twitter", "wikipedia", "ddg"]
            },
            "filters": {
              "sampleRate": 100,
              "products": ["firefox"],
              "channels": ["esr"],
              "minVersion": 60
            },
            "interval": 86400
          }
        }
```

The first cohort is always picked even if you specify a version of 60. I would expect the test code to be smart enough to pick the cohort based on the minVersion and not just go down the first path.

Changing the order in the file has no effect.

We need the ability to say "always use this engine set for 60+" but it's not possible right now.

**Comment by leplatrem** [comment]
Maybe the cohors should be sorted by `minVersion` here:
https://github.com/mozilla-services/absearch/blob/5a997f46028900a44fca7a25c5ef656f8f3ba2cb/absearch/settings.py#L254

**Comment by mkaply** [comment]
Unfortunately at that point all we have is the cohort strings.

I'm wondering if we should not even add the cohort to the list if there is a 100% with a higher minVersion?

**Comment by tiftran** [comment]
Closing as this issue has been around for a while, not sure of current relevance, will reopen if there’s a need for it
