### ISSUE TITLE
locale fallback for weird locale codes

### ISSUE THREAD

**Issue by mconnormoz** [mozilla-services/absearch#5]
Linux builds sometimes end up with locale codes like fr-FR instead of fr.  Rather than bloat the config, I'd like us to have a fallback where if ab-CD isn't found, we look for ab.

Not urgent, but we'd want it before we ship.

**Comment by tarekziade** [comment]
I guess you are talking about the region, not the locale. I will change accordingly so : 

```
/1/firefox/39/beta/cs-CZ/cz-TU/default/default
```

Falls back to 

```
/1/firefox/39/beta/cs-CZ/cz/default/default
```

for example

**Comment by fqueze** [comment]
I'm pretty sure Mike is really talking about the locale. The region is something returned by mozilla geoip servers, so it's fully within our control and should always be 2 characters.

**Comment by tarekziade** [comment]
I need a full example. e.g. how you call the service, and the fallback call

**Comment by fqueze** [comment]
https://search.stage.mozaws.net/1/Firefox/39/release/fr/FR/default/default is the normal call from a normal French build.

https://search.stage.mozaws.net/1/Firefox/39/release/fr-FR/FR/default/default is a call that could happen from a Linux distribution

"fr" and "fr-FR" are both valid locale codes. Mike is saying he wants to specify only "fr" in the config file, and have it work for both. Or really have it work for fr and fr-*

What Mike is asking is: "if the locale ab-CD isn't found in the config file, please check if the locale ab exists before falling back to the fully generic default".

**Comment by tarekziade** [comment]
Thanks for the clarification - I have reimplemented accordingly.
