### ISSUE TITLE
search.stage.mozaws.net has failed the web security baseline

### ISSUE THREAD

**Issue by moz-hwine** [mozilla-services/absearch#62]
Site https://search.stage.mozaws.net has failed the web security baseline scan.

The failing tests are:

 X-Frame-Options Header Not Set [10020] x 1 
 * https://search.stage.mozaws.net/__api__ (200 OK)

 X-Content-Type-Options Header Missing [10021] x 2 
 * https://search.stage.mozaws.net/__api__ (200 OK)
 * https://search.stage.mozaws.net/ (200 OK)

 Strict-Transport-Security Header Not Set [10035] x 2 
 * https://search.stage.mozaws.net/robots.txt (404 Not Found)
 * https://search.stage.mozaws.net/sitemap.xml (404 Not Found)

 Content Security Policy (CSP) Header Not Set [10038] x 3 
 * https://search.stage.mozaws.net/__api__ (200 OK)
 * https://search.stage.mozaws.net/robots.txt (404 Not Found)
 * https://search.stage.mozaws.net/sitemap.xml (404 Not Found)

This issue was automatically raised.

This issue is managed automatically by the baseline scan:

 * If the failing tests change then it will be updated
 * If it is closed before the tests pass then a new one will be opened
 * When all of the tests pass then it will be closed

Full details, including how to test for these issues locally, can be found on this [Security Baseline Service](https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=search.stage.mozaws.net) dashboard.
If you have any questions or concerns please get in contact with @psiinon

**Comment by moz-hwine** [comment]
The following test(s) for site https://search.stage.mozaws.net have now passed:

 * X-Frame-Options Header Not Set

Keep up the good work!

**Comment by moz-hwine** [comment]
The following test(s) for site https://search.stage.mozaws.net have now passed:

 * X-Content-Type-Options Header Missing

Keep up the good work!

**Comment by moz-hwine** [comment]
The web security baseline scan results for site https://search.stage.mozaws.net has new failures:


 X-Content-Type-Options Header Missing [10021] x 1 
 * https://search.stage.mozaws.net/ (200 OK)

**Comment by moz-hwine** [comment]
The following test(s) for site https://search.stage.mozaws.net have now passed:

 * X-Content-Type-Options Header Missing

Keep up the good work!

**Comment by moz-hwine** [comment]
The web security baseline scan results for site https://search.stage.mozaws.net has new failures:


 X-Content-Type-Options Header Missing [10021] x 1 
 * https://search.stage.mozaws.net/ (200 OK)

**Comment by moz-hwine** [comment]
The following test(s) for site https://search.stage.mozaws.net have now passed:

 * X-Content-Type-Options Header Missing

Keep up the good work!

**Comment by moz-hwine** [comment]
The web security baseline scan results for site https://search.stage.mozaws.net has new failures:


 X-Content-Type-Options Header Missing [10021] x 1 
 * https://search.stage.mozaws.net/ (200 OK)

**Comment by moz-hwine** [comment]
The following test(s) for site https://search.stage.mozaws.net have now passed:

 * Content Security Policy (CSP) Header Not Set

Keep up the good work!

**Comment by tiftran** [comment]
Closing as this issue has been around for a while, not sure of current relevance, will reopen if there’s a need for it

**Comment by moz-hwine** [comment]
The web security baseline for site https://search.stage.mozaws.net is still failing, this issue should stay open.

**Comment by tiftran** [comment]
hi @hwine, was wondering if you could provide advice on what these header values should be?

**Comment by hwine** [comment]
@g-k - can you help explain the results, please?  (@tiftran my account only runs the automation)

**Comment by g-k** [comment]
Sure, some of the mentioned URLs aren't returning security headers: 

`X-Frame-Options Header Not Set [10020] x 1` refers to this alert https://www.zaproxy.org/docs/alerts/10020-1/ and you can test it with:

```console
curl -I 'https://search.stage.mozaws.net/__api__'
HTTP/1.1 404 Not Found
Content-Length: 0
Content-Type: application/json
Date: Tue, 02 Mar 2021 15:51:52 GMT
Connection: keep-alive
```


These are 404s and an API endpoint, so we probably want:

```
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Strict-Transport-Security: 15768000
Content-Security-Policy: default-src 'none'; frame-ancestors 'none'
```

If nginx or another reverse proxy is running in front of the app and serving requests then we'd probably want to Ops for the service to add the headers in the nginx config.

There's additional explanatory info for the headers and values at:

https://infosec.mozilla.org/guidelines/web_security#x-frame-options
https://infosec.mozilla.org/guidelines/web_security#x-content-type-options
https://infosec.mozilla.org/guidelines/web_security#http-strict-transport-security
https://infosec.mozilla.org/guidelines/web_security#content-security-policy

**Comment by tiftran** [comment]
Thanks @g-k !

**Comment by moz-hwine** [comment]
The following test(s) for site https://search.stage.mozaws.net have now passed:

 * X-Content-Type-Options Header Missing

Keep up the good work!

**Comment by moz-hwine** [comment]
The web security baseline scan for site https://search.stage.mozaws.net now passes - well done team!
