### ISSUE TITLE
search.services.mozilla.com has failed the web security baseline

### ISSUE THREAD

**Issue by moz-hwine** [mozilla-services/absearch#63]
Site https://search.services.mozilla.com has failed the web security baseline scan.

The failing tests are:

 X-Frame-Options Header Not Set [10020] x 1 
 * https://search.services.mozilla.com/__api__ (200 OK)

 X-Content-Type-Options Header Missing [10021] x 2 
 * https://search.services.mozilla.com/__api__ (200 OK)
 * https://search.services.mozilla.com/ (200 OK)

 Strict-Transport-Security Header Not Set [10035] x 2 
 * https://search.services.mozilla.com/robots.txt (404 Not Found)
 * https://search.services.mozilla.com/sitemap.xml (404 Not Found)

 Content Security Policy (CSP) Header Not Set [10038] x 3 
 * https://search.services.mozilla.com/__api__ (200 OK)
 * https://search.services.mozilla.com/robots.txt (404 Not Found)
 * https://search.services.mozilla.com/sitemap.xml (404 Not Found)

This issue was automatically raised.

This issue is managed automatically by the baseline scan:

 * If the failing tests change then it will be updated
 * If it is closed before the tests pass then a new one will be opened
 * When all of the tests pass then it will be closed

Full details, including how to test for these issues locally, can be found on this [Security Baseline Service](https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=search.services.mozilla.com) dashboard.
If you have any questions or concerns please get in contact with @psiinon

**Comment by moz-hwine** [comment]
The following test(s) for site https://search.services.mozilla.com have now passed:

 * X-Frame-Options Header Not Set

Keep up the good work!

**Comment by moz-hwine** [comment]
The web security baseline scan results for site https://search.services.mozilla.com has new failures:


 X-Frame-Options Header Not Set [10020] x 1 
 * https://search.services.mozilla.com/__api__ (200 OK)

**Comment by moz-hwine** [comment]
The following test(s) for site https://search.services.mozilla.com have now passed:

 * X-Frame-Options Header Not Set

Keep up the good work!

**Comment by moz-hwine** [comment]
The following test(s) for site https://search.services.mozilla.com have now passed:

 * X-Content-Type-Options Header Missing

Keep up the good work!

**Comment by moz-hwine** [comment]
The web security baseline scan results for site https://search.services.mozilla.com has new failures:


 X-Content-Type-Options Header Missing [10021] x 1 
 * https://search.services.mozilla.com/ (200 OK)

**Comment by moz-hwine** [comment]
The following test(s) for site https://search.services.mozilla.com have now passed:

 * Content Security Policy (CSP) Header Not Set

Keep up the good work!

**Comment by tiftran** [comment]
Closing as this issue has been around for a while, not sure of current relevance, will reopen if there’s a need for it

**Comment by moz-hwine** [comment]
The web security baseline for site https://search.services.mozilla.com is still failing, this issue should stay open.

**Comment by moz-hwine** [comment]
The web security baseline scan for site https://search.services.mozilla.com now passes - well done team!
