### ISSUE TITLE
What should we tell ops when S3 is broken ?

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/absearch#8]
The app will still work with the existing config but we should poke ops since a new version won't be loaded.

https://github.com/mozilla-services/absearch/blob/master/absearch/settings.py#L83

Dean, Bob, what should we add there ? thx

**Comment by Micheletto** [comment]
Is this an error because it failed to parse properly, or because it was unable to read from S3?

**Comment by tarekziade** [comment]
failed to reach S3

**Comment by tiftran** [comment]
Closing as this issue has been around for a while, not sure of current relevance, will reopen if there’s a need for it
