### ISSUE TITLE
Remove absearch.cohorts.locale.* metrics

### ISSUE THREAD

**Issue by Micheletto** [mozilla-services/absearch#9]
We need to stop forwarding these metrics, or send them to a dedicated Graphite host like location does.  The volume is overwhelming our metrics service.

**Comment by Natim** [comment]
Does changing for ``absearch.cohorts.locale_territory_cohort`` would help?

**Comment by Micheletto** [comment]
I've deployed this current version to our staging environment for preliminary testing.

**Comment by Micheletto** [comment]
> I've deployed this current version to our staging environment for preliminary testing.

@stuartphilp tested this deploy, and I believe it looked good.
@leplatrem where are we at in getting this merged?

**Comment by Natim** [comment]
@Micheletto we'd like to fix travis build first. @tarekziade said it will have a look at it this week.

**Comment by hannosch** [comment]
FYI: Location stopped using a dedicated graphite instance and is only using datadog. We do use datadog "tags" though, via the datadog specific dogstatsd library (http://docs.datadoghq.com/guides/dogstatsd/#tags). This helps in keeping the number of visible metrics down in the datadog UI, while still being able to query and group by the actual values. They have more info on this in http://docs.datadoghq.com/guides/metrics/.

**Comment by ametaireau** [comment]
Thanks for the info @hannosch. @Micheletto would you like us to use Datadog instead of graphite?

**Comment by hannosch** [comment]
I was assuming that the "metrics service" mentioned by @Micheletto is datadog. At least I see all the "absearch.cohorts.*" metrics in the production datadog service.

**Comment by Micheletto** [comment]
> Thanks for the info @hannosch. @Micheletto would you like us to use Datadog instead of graphite?

In any case, tagged key + value combinations use up our metrics allotment.  I don't think we actually need the cohorts.* stats for anything, do we?

**Comment by Micheletto** [comment]
> Thanks for the info @hannosch. @Micheletto would you like us to use Datadog instead of graphite?
We are using Datadog presently.  We're adding a bunch of stats that we don't need, nor do I think we need the information even if it is coded in tags.  At any rate, unique tag key and value combinations cost us an available metric because of how they store the data.
